# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4910b37dbc9a02bc6809722299043e3a1c4db93156ec5b6123c503c7e6f758b95e52401b729a5b782c147a802d973f0e58cba9d1777d6701c24cde58027bef9

test:
  secret_key_base: d9d79e4783f402c99f750c6258e8a15e6432a6a1bb972925c5f8061b59256408b5ac2e9fcaa1eb83433d6dce6bdbafcac52757b5e21fd63b3dd9f27611801802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
